apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170972098
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170972098
    app.kubernetes.io/part-of: test-app-170972098
  name: java-quarkus-170972098
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170972098
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170972098
    spec:
      containers:
      - image: quay.io/hacdev/vukzv9wt-tenant/test-app-170972098/java-quarkus-170972098@sha256:190ce4ffe7a059d5556d16fb90d2d3ef1bb840fb458971c311c55632c8c60629
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
